version: b{build}

os: Visual Studio 2015

branches:
  except:
    - gh-pages

init:
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1
  - SET ANSICON=121x90 (121x90)

install:
  - python -V

build_script:
  - cmd: call make.bat

after_build:
  - make dist

test_script:
  - "cd node && npm install"
  - cmd: make integration

artifacts:
  - path: Watchman
    name: watchman
    type: zip

environment:
  matrix:
    - WATCHMAN_WIN7_COMPAT: 1
    - WATCHMAN_WIN7_COMPAT:

platform:
  - x64
